version: '3.8'

services:
  www_symfony_5:
    build: docker/php
    container_name: symfony_5
    ports:
      - "80:80"
    volumes:
      - ./docker/php/conf.d/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./:/srv/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - symfony_5

networks:
  symfony_5:
