version: '3.8'

services:
  database_symfony_5:
    image: mysql:5.6.51
    container_name: database_symfony_5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${DB_PATH}:/var/lib/mysql:cached
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - symfony_5

  www_symfony_5:
    build: docker/php
    container_name: symfony_5
    depends_on:
      - database_symfony_5
      - mercure_symfo_5
    links:
      - database_symfony_5
      - mercure_symfo_5
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./docker/php/conf.d/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/conf.d/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./:/srv/app
      - ./docker/php/cert/mycert.crt:/etc/ssl/certs/mycert.crt
      - ./docker/php/cert/mycert.key:/etc/ssl/private/mycert.key
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - symfony_5

  ###> symfony/mailer ###
#  mailer:
#    image: schickling/mailcatcher
#    ports: [ "1025", "1080" ]
  ###< symfony/mailer ###

###> symfony/mercure-bundle ###
  mercure_symfo_5:
    image: dunglas/mercure
    container_name: mercure_symfo_5
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_SECRET}
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins https://127.0.0.1:443
      # Comment the following line to enable HTTPS
      SERVER_NAME: ':80'
    ports:
      - ${HTTP_MERCURE_PORT}:80
      - ${HTTPS_MERCURE_PORT}:443
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    networks:
      - symfony_5
###< symfony/mercure-bundle ###

networks:
  symfony_5:

volumes:
###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
