version: '3.8'

services:
  database_symfony_5:
    image: mysql:5.6.51
    container_name: database_symfony_5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - symfony_5

  www_symfony_5:
    build: docker/php
    container_name: symfony_5
    depends_on:
      - database_symfony_5
    links:
      - database_symfony_5
    ports:
      - "80:80"
    volumes:
      - ./docker/php/conf.d/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./:/srv/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - symfony_5

networks:
  symfony_5:
