App\Entity\ApiToken:
  attributes:
    id:
      groups: ['api:api_token:read']
    user:
      groups: [ 'api:api_token:admin_read' ]
    identifier:
      groups: ['api:api_token:read']
    createdAt:
      groups: ['api:api_token:read']
    lastUsedAt:
      groups: ['api:api_token:read']