App\Entity\Spell:
  attributes:
    id:
      groups: [ 'api:spell' ]
    name:
      groups: ['api:spell', 'api:spell:details']
    constant_code:
      groups: ['api:spell', 'api:spell:details']
    owner:
      groups: ['api:spell:details']