App\Entity\Spell:
  attributes:
    name:
      groups: ['api:spell', 'api:spell:details']
    constant_code:
      groups: ['api:spell', 'api:spell:details']
    owner:
      groups: ['api:spell:details']