v1_api_controllers:
  resource: ../src/Controller/API/V1
  type: annotation
  prefix: /api/v1

v2_api_controllers:
  resource: ../src/Controller/API/V2
  type: annotation
  prefix: /api/v2
  name_prefix: api_v2_