# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.cache_ttl: 3600
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            int $cacheTTL: '%app.cache_ttl%'
            $formLoginAuthenticator: '@security.authenticator.form_login.main'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
            - '../src/Service/Markdown/MarkdownConverter.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.markdown.converter:
        class: App\Service\Markdown\MarkdownConverter
    App\Service\Markdown\MarkdownConverterInterface: '@app.markdown.converter'

    App\Security\ApiTokenAuthenticator:
        arguments:
            $authTokenHeader: '%env(API_TOKEN_HEADER)%'
